#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  defaults:
    _controller: AppBundle:Default:index

ajax_route:
  path:     /ajax_request
  defaults:
    _controller: AppBundle:Default:ajax
  methods: [post]

